### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property '_bn' of undefined

### ISSUE THREAD

**Issue by Sylor-huang** [phantom-labs/sandbox#10]
Hi, when I run sandbox code in localhost, I get this errors:

```js
src/App.tsx
  Line 42:30:  Parsing error: Unexpected token, expected ","

...
Uncaught (in promise) TypeError: Cannot read property '_bn' of undefined
```

The same error in the codesandbox:

![image](https://user-images.githubusercontent.com/26167245/131855766-38e1535e-a61e-44fb-8a6e-70d13d4e0008.png)

How to solve the problem? thanks~

**Comment by fragosti** [comment]
Click "x" I think we need to update a dependency.

**Comment by fragosti** [comment]
Actually it's fixed now with the latest merge.
